[package]
name = "threefish_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
threefish = "0.5.2"
rand = "0.8"
zeroize = "1.5"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
indicatif = "0.17"