[package]
name = "filecrypt"
version = "0.1.0"
edition = "2024"

[dependencies]
sodiumoxide = { version = "0.2.7", features = ["bundled"] }
clap       = { version = "4.5.37", features = ["derive"] }

