# Cargo.toml
[package]
name = "ezaes"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm-siv = "0.11.1"    # AES-256-GCM-SIV implementation
rand       = "0.9.1"      # for secure nonce generation
